name: github-actions auto-approve
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-bot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'semgrep-ci[bot]'}}
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
