jobs:
  tag-version:
    runs-on: ubuntu-latest
    if: ${{contains(github.event.head_commit.message, 'Bump setup')}}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      checks: write
    steps:
      - id: jwt
        env:
          EXPIRATION: 600
          ISSUER: ${{ secrets.SEMGREP_CI_APP_ID }}
          PRIVATE_KEY: ${{ secrets.SEMGREP_CI_APP_KEY }}
        name: Get JWT for semgrep-ci GitHub App
        uses: docker://public.ecr.aws/y9k7q4m1/devops/cicd:latest

      - id: token
        name: Get token for semgrep-ci GitHub App
        run: |
          TOKEN="$(curl -X POST \
          -H "Authorization: Bearer ${{ steps.jwt.outputs.jwt }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/app/installations/${{ secrets.SEMGREP_CI_APP_INSTALLATION_ID }}/access_tokens" | \
          jq -r .token)"
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Bump version in this repo
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: scripts/tag-version.sh "${NEW_SEMGREP_VERSION}"

name: tag-version
on:
  push:
    branches:
      - develop
